### ISSUE TITLE
以.github.io为前缀的pdf文件

### ISSUE THREAD

**Issue by Accelerator086** [taroxd/taroxd.github.io#2]
您好，我看到《被卷入了勇者召唤事件却发现异世界很和平》第八卷的pdf链接前缀是github.io，以及《关于邻家的天使大人不知不觉把我惯成了废人这档子事》的pdf也是有github.io的前缀，但是在博客以及此repo里并没有找到这一pdf文件，我想问一下这是怎么做到的呢？谢谢您！
https://taroxd.github.io/n2273dh/n2273dh_08.pdf

**Comment by taroxd** [comment]
天使来自 https://github.com/taroxd/n8440fe/tree/gh-pages ，
和平来自一个 private repo。

这些文件使用了 project 的 GitHub Pages，参考相关帮助：https://help.github.com/en/github/working-with-github-pages/about-github-pages#types-of-github-pages-sites

> The source files for a project site are stored in the same repository as their project. Unless you're using a custom domain, project sites are available at http(s)://\<user\>.github.io/\<repository\> or http(s)://\<organization\>.github.io/\<repository\>.
